<?php

namespace Fly\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    public function findForGroup($group, $limit, $lastId = 0, $refresh = null, $lastTime = 0,  $query = false)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.resource','resource')
            ->where('f.group = :group')
            ->setMaxResults($limit)
        ;

        $qb->setParameter('group',$group);

        if($refresh){

            $date = new \DateTime();
            $lastDate = $date->setTimestamp($lastTime);
            $qb->andWhere('f.created > :lastDate')
                ->setParameter('lastDate',$lastDate)
            ->orderBy('f.created','DESC');
        }else{
            if($lastId > 0){
                $qb->andWhere('f.id < :lastId');
            }else{
                $qb->andWhere('f.id > :lastId');
            }

            $qb->setParameter('lastId',$lastId)
                ->orderBy('f.id','DESC')
                ;
        }


        if($query){
            return $qb;
        }
        return $qb->getQuery()->getResult();
    }




}
