<?php

namespace Fly\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedLikeRepository extends EntityRepository
{

    public function getByUserFeed($feed, $user)
    {
        return $this->createQueryBuilder('l')
            ->where('l.user = :user')->setParameter('user',$user)
            ->andWhere('l.feed = :feed')->setParameter('feed',$feed)
            ->getQuery()->getResult();
    }

}
