<?php

namespace Fly\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedCommentRepository extends EntityRepository
{
}
