<?php

namespace Fly\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function findGroupsWithInvites($user, $query = true)
    {
        $qb = $this->createQueryBuilder('g')
            ->leftJoin('g.users','user')
            ->leftJoin('g.invitation', 'invitation')
            ->where('user = :user')
            ->orWhere('invitation.user = :user')
            ->orderBy('g.created','DESC');

        $qb->setParameter('user',$user);
//        $qb->setParameter('email',$user->getEmail());

        if($query){
            return $qb;
        }
        return $qb->getQuery()->getResult();
    }




}
