<?php

namespace Fly\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getUserNotificationsQuery($user)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.user = :user')
            ->setParameters(['user'=>$user])
            ->orderBy('n.created','DESC');

        return $qb;
    }

    public function updateUnread($ids){
        $qb = $this->createQueryBuilder('n')
            ->update()
            ->set('n.is_read','1')
            ->where('n.id IN (:ids)')
            ->setParameters(['ids'=>$ids])
            ;
        $qb->getQuery()->execute();
    }
}
