<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccItemRepository extends EntityRepository
{
    public function getItemsByMonth()
    {
        $monthStart = new \DateTime();
        $monthEnd = new \DateTime();

        $qb = $this->createQueryBuilder('accItem')
//            ->where('accItem.checkin >= :mothStart')
//            ->andWhere('accItem.checkin <= :monthEnd')
//            ->setParameters(['mothStart'=>$monthStart, 'monthEnd'=>$monthEnd])
            ;

        return $qb->getQuery()->getResult();
    }
}
