<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccomodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccomodationRepository extends EntityRepository
{
}
