<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportRepository extends EntityRepository
{
    public function filters($q)
    {
        return $query = $this->createQueryBuilder('a')
            ->where('a.city_name LIKE :q')->setParameter('q', $q . '%')
            ->getQuery()->getResult();
    }
}
