<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlyCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlyCacheRepository extends EntityRepository
{
    public function checkCacheData($a1, $a2, $d1, $d2)
    {

        $qb = $this->createQueryBuilder('c')
            ->where('c.airport_one = :a1')
            ->andWhere('c.airport_two = :a2')
            ->andWhere('c.departure_out = :d1')
            ->andWhere('c.departure_in = :d2')
            ;

        $qb->setParameters([
            'a1'=>$a1,
            'a2'=>$a2,
            'd1'=>$d1,
            'd2'=>$d2,
        ]);
//dump($a1, $a2, $d1, $d2,$qb->getQuery()->getSQL()); die;
        $query =  $qb->getQuery()
            ->useQueryCache(true)    // here
            ->useResultCache(true);

        $res = $query->getOneOrNullResult();

        if($res){
            $data = [
                'recommendations'=>$res->getRecommendation(),
                'outbounds'=>$res->getOutbound(),
                'inbounds'=>$res->getInbound(),
            ];

            return $data;
        }

        return $res;
    }
}
