<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlyInsuranceOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlyInsuranceOrderRepository extends EntityRepository
{


    public function getArrayed()
    {
        return $this->createQueryBuilder('i')
           ->select('i.id, i.insurance, i.name')
            ->orderBy('i.insurance', 'ASC')
            ->getQuery()->getArrayResult();

    }

}
