<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlyOrderRepository extends EntityRepository
{

    public function getUserWalletQuery($user)
    {
        return $this->createQueryBuilder('o')
            ->where('o.email = :useremail')
            ->setParameter('useremail',$user->getEmail())
            ->getQuery();
    }

}
