<?php

namespace Fly\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportationRepository extends EntityRepository
{
}
